### ISSUE TITLE
csv problem

### ISSUE THREAD

**Issue by ghost** [Saschax99/WebScraperAsync#1]
Traceback (most recent call last):
  File "/home/ubuntu/WebScraperAsync/main.py", line 72, in <module>
    resultsCheck(res)
  File "/home/ubuntu/WebScraperAsync/main.py", line 36, in resultsCheck
    title = sess.html.xpath("//h1[@class='text-center text-wordwrap']", first=True).text
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by Saschax99** [comment]
fixed in v1.2
