### ISSUE TITLE
lxml.etree.ParserError: Document is empty       

### ISSUE THREAD

**Issue by ghost** [Saschax99/WebScraperAsync#2]
Traceback (most recent call last):                                                                                    
  File "/home/kali/.local/lib/python3.10/site-packages/pyquery/pyquery.py", line 57, in fromstring                    
    result = getattr(etree, meth)(context)                                                                            
  File "src/lxml/etree.pyx", line 3252, in lxml.etree.fromstring                                                      
  File "src/lxml/parser.pxi", line 1913, in lxml.etree._parseMemoryDocument                                           
  File "src/lxml/parser.pxi", line 1800, in lxml.etree._parseDoc                                                      
  File "src/lxml/parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc                                          
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc                            
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult                                              
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError                                                
  File "<string>", line 1                                                                                             
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1                                                        
                                                                                                                      
During handling of the above exception, another exception occurred:                                                   
                                                                                                                      
Traceback (most recent call last):                                                                                    
  File "/home/kali/Desktop/WebScraperAsync/main.py", line 94, in <module>                                             
    res = asyncio.run(main())                                                                                         
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run                                                      
    return loop.run_until_complete(main)                                                                              
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete                                  
    return future.result()                                                                                            
  File "/home/kali/Desktop/WebScraperAsync/main.py", line 69, in main                                                 
    return await asyncio.gather(*file_url)                                                                            
  File "/home/kali/Desktop/WebScraperAsync/main.py", line 52, in work                                                 
    if len(session.html.xpath("//h1[@class='text-center']")) > 0 and len(                                             
  File "/home/kali/.local/lib/python3.10/site-packages/requests_html.py", line 654, in html                           
    self._html = HTML(session=self.session, url=self.url, html=self.content, default_encoding=self.encoding)          
  File "/home/kali/.local/lib/python3.10/site-packages/requests_html.py", line 421, in __init__                       
    element=PyQuery(html)('html') or PyQuery(f'<html>{html}</html>')('html'),                                         
  File "/home/kali/.local/lib/python3.10/site-packages/pyquery/pyquery.py", line 217, in __init__                     
    elements = fromstring(context, self.parser)                                                                       
  File "/home/kali/.local/lib/python3.10/site-packages/pyquery/pyquery.py", line 61, in fromstring                    
    result = getattr(lxml.html, meth)(context)                                                                        
  File "/usr/lib/python3/dist-packages/lxml/html/__init__.py", line 875, in fromstring                                
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)                                           
  File "/usr/lib/python3/dist-packages/lxml/html/__init__.py", line 763, in document_fromstring                       
    raise etree.ParserError(                                                                                          
lxml.etree.ParserError: Document is empty

**Comment by Saschax99** [comment]
changed the encoding to 'iso-8859-1' when reading and writing the files, which will probably fix the error.
